channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.0
- pip:
  - mlflow==2.13.2
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - jinja2==3.1.3
  - numpy==1.26.1
  - optree==0.11.0
  - packaging==24.0
  - pandas==2.2.2
  - pyyaml==6.0.1
  - scipy==1.13.0
  - torch-geometric==2.5.3
  - torch==2.3.1
name: mlflow-env
